[window]
decorations = "None"
startup_mode = "Fullscreen"

[terminal]
shell = { program = "/usr/bin/fish", args = ["-l", "-c", "tmux -u"] }

# Let Alacritty use its default TERM value
# [env]
# TERM = "xterm-256color"

[mouse]
hide_when_typing = true

[font]
normal = {family = "JetBrainsMono Nerd Font", style = "Regular" }
italic = {family = "JetBrainsMono Nerd Font", style = "Italic" }

