[window]
decorations = "None"
startup_mode = "Maximized"

[terminal]
shell = { program = "/usr/bin/fish", args = ["-l", "-c", "tmux -u"] }

# Let Alacritty use its default TERM value
# [env]
# TERM = "xterm-256color

[mouse]
hide_when_typing = true

[font]
normal = {family = "JetBrainsMono Nerd Font", style = "Regular" }
italic = {family = "JetBrainsMono Nerd Font", style = "Italic" }


[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Control"
